export const Majors = [
    {label: 'Agriculture', value: 'Agriculture'},
    {label: 'Architecture', value: 'Architecture'},
    {label: 'Art', value: 'Art'},
    {label: 'Biological Sciences', value: 'Biological Sciences'},
    {label: 'Business', value: 'Business'},
    {label: 'Communication', value: 'Communication'},
    {label: 'Computer Science', value: 'Computer Science'},
    {label: 'Criminal Justice', value: 'Criminal Justice'},
    {label: 'Education', value: 'Education'},
    {label: 'Engineering', value: 'Engineering'},
    {label: 'English', value: 'English'},
    {label: 'Environmental Science', value: 'Environmental Science'},
    {label: 'Health', value: 'Health'},
    {label: 'History', value: 'History'},
    {label: 'Humanities', value: 'Humanities'},
    {label: 'Journalism', value: 'Journalism'},
    {label: 'Law', value: 'Law'},
    {label: 'Mathematics', value: 'Mathematics'},
    {label: 'Medicine', value: 'Medicine'},
    {label: 'Music', value: 'Music'},
]

export const Minors = [
    {label: 'Agriculture', value: 'Agriculture'},
    {label: 'Architecture', value: 'Architecture'},
    {label: 'Art', value: 'Art'},
    {label: 'Biological Sciences', value: 'Biological Sciences'},
    {label: 'Business', value: 'Business'},
    {label: 'Communication', value: 'Communication'},
    {label: 'Computer Science', value: 'Computer Science'},
    {label: 'Criminal Justice', value: 'Criminal Justice'},
    {label: 'Education', value: 'Education'},
    {label: 'Engineering', value: 'Engineering'},
    {label: 'English', value: 'English'},
    {label: 'Environmental Science', value: 'Environmental Science'},
    {label: 'Health', value: 'Health'},
    {label: 'History', value: 'History'},
    {label: 'Humanities', value: 'Humanities'},
    {label: 'Journalism', value: 'Journalism'},
    {label: 'Law', value: 'Law'},
    {label: 'Mathematics', value: 'Mathematics'},
    {label: 'Medicine', value: 'Medicine'},
    {label: 'Music', value: 'Music'},
]

export const Year = [
    {label: 'Freshman', value: 'Freshman'},
    {label: 'Sophomore', value: 'Sophomore'},
    {label: 'Junior', value: 'Junior'},
    {label: 'Senior', value: 'Senior'},
    {label: 'Graduate', value: 'Graduate'},
]
