const categories = [
    { label: 'Books', value: 'Books' },
    { label: 'Electronics', value: 'Electronics' },
    { label: 'Clothing', value: 'Clothing' },
    { label: 'Accessories', value: 'Accessories' },
    { label: 'Furniture', value: 'Furniture' },
    { label: 'Stationery', value: 'Stationery' },
    { label: 'Musical Instruments', value: 'Musical Instruments' },
    { label: 'Sports Equipment', value: 'Sports Equipment' },
    { label: 'Appliances', value: 'Appliances' },
    { label: 'Home Decor', value: 'Home Decor' },
    { label: 'Art Supplies', value: 'Art Supplies' },
    { label: 'Kitchenware', value: 'Kitchenware' },
    { label: 'Fitness Gear', value: 'Fitness Gear' },
    { label: 'Gadgets', value: 'Gadgets' },
    { label: 'Beauty and Personal Care', value: 'Beauty and Personal Care' },
    { label: 'School Supplies', value: 'School Supplies' },
    { label: 'Board Games', value: 'Board Games' },
    { label: 'Outdoor Gear', value: 'Outdoor Gear' },
    { label: 'Textbooks', value: 'Textbooks' },
    { label: 'Shoes', value: 'Shoes' },
    { label: 'Bags and Backpacks', value: 'Bags and Backpacks' },
    { label: 'Health and Wellness', value: 'Health and Wellness' },
    { label: 'DIY and Crafts', value: 'DIY and Crafts' },
    { label: 'Photography Equipment', value: 'Photography Equipment' },
    { label: 'Gaming Consoles and Accessories', value: 'Gaming Consoles and Accessories' },
    { label: 'Collectibles', value: 'Collectibles' },
    { label: 'Party Supplies', value: 'Party Supplies' },
    { label: 'Travel Accessories', value: 'Travel Accessories' },
    { label: 'Instruments and Tools', value: 'Instruments and Tools' },
    { label: 'Pet Supplies', value: 'Pet Supplies' }
];

export default categories;
